import {Food} from './app/shared/models/food';
import {Tag} from './app/shared/models/Tag';
export const sample_foods: Food[]= [
  {
      id:'1',
      name:'chicken',
      price:11,
      cookTime:'40-50',
      favorite: false,
      origins:['india','asia'],
      stars: 3.0,
      imageUrl:'assets/food-1.jpeg',
      tags:['SlowFood','Soup'],
  },
  {
    id:'2',
    name:'soup',
    price:11,
    cookTime:'40-50',
    favorite: false,
    origins:['india','asia'],
    stars: 3.0,
    imageUrl:'assets/food-2.jpeg',
    tags:['SlowFood','Soup'],
},
{
    id:'3',
    name:'soup',
    price:11,
    cookTime:'40-50',
    favorite: false,
    origins:['india','asia'],
    stars: 3.0,
    imageUrl:'assets/food-3.jpeg',
    tags:['SlowFood','Soup'],
},
{
    id:'4',
    name:'pizza',
    price:11,
    cookTime:'40-50',
    favorite: false,
    origins:['india','asia'],
    stars: 3.0,
    imageUrl:'assets/food-4.jpeg',
    tags:['SlowFood','Soup'],
},
{
    id:'5',
    name:'mixed',
    price:11,
    cookTime:'40-50',
    favorite: false,
    origins:['india','asia'],
    stars: 3.0,
    imageUrl:'assets/food-5.jpeg',
    tags:['SlowFood','Soup'],
},

  
]
export const sample_tags:Tag[]=[
    { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]